id: P005634
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS60779
  title: ག་རྒྱ་ཁྱུང་སྤྲུལ་སྨན་གཞུང
  author: ''
  volumes:
    058a22b0a3f8463e8a83f1df23fa264a:
      image_group_id: I1GS60781
      title: ''
      volume_number: 1
      total_pages: 674
    df47581955df4cf6b830bc9f761141e4:
      image_group_id: I1GS60782
      title: ''
      volume_number: 2
      total_pages: 510
